# development:
#   adapter: mysql
#   database: piecemaker
#   username: root
#   password: swordfis
#   encoding: utf8
#   socket: /tmp/mysql.sock
# #   
# production:
#   adapter: mysql
#   database: piecemaker
#   username: root
#   password: swordfis
#   encoding: utf8
#   socket: /tmp/mysql.sock
#   
# development:
#   adapter: mysql
#   database: piecemaker
#   username: root
#   password: swordfis
#   encoding: utf8
#   socket: /tmp/mysql.sock

development:
  adapter: postgresql
  database: piecemaker
  username: davidkern
  host: localhost
  password: swordfis
  encoding: utf8
  socket: /var/pgsql_socket/.s.PGSQL.5432
# development:
#   adapter: sqlite3
#   database: db/databases/piecemaker_starter
#   encoding: utf8
# production:
#   adapter: sqlite3
#   database: db/databases/piecemaker_starter
#   encoding: utf8
# development:
#   adapter: sqlite3
#   database: db/databases/piecemaker_prod
#   encoding: utf8
# production:
#   adapter: sqlite3
#   database: db/databases/piecemaker_prod
#   encoding: utf8

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
# test:
#   adapter: sqlite3
#   database: db/databases/piecemaker_test
#   encoding: utf8

