{"command"=>{
"class"=>"Event",
"ivars"=> {
  "attributes"=>{
    "id"=>28102,
    "title"=>"Performance of Demonstrationxxx",
    "happened_at"=>"2012-09-12T08:14:51Z",
    "dur"=>nil,
    "event_type"=>"performance_notes",
    "video_id"=>28101,
    "piece_id"=>105,
    "locked"=>"none",
    "state"=>"normal",
    "description"=>"",
    "created_by"=>"David",
    "modified_by"=>"Dav",
    "updated_at"=>"2013-05-03T13:25:10Z",
    "performers"=>nil,
    "created_at"=>"2012-09-12T08:14:50Z",
    "highlighted"=>false,
    "inherits_title"=>false,
    "location"=>nil,
    "rating"=>0,
    "parent_id"=>nil,
    "account_id"=>nil}
    }}